// Import React hook for state management
import { useState } from "react";

// Import navigation hook from react-router
import { useNavigate } from "react-router-dom";

function Login() {

  // 🔹 Store username input
  const [username, setUsername] = useState("");

  // 🔹 Store password input
  const [password, setPassword] = useState("");

  // 🔹 Store status message (success/error)
  const [status, setStatus] = useState("");

  // 🔹 Track if error message should be shown in red
  const [error, setError] = useState(false);

  // 🔹 OTP entered by user
  const [otp, setOtp] = useState("");

  // 🔹 OTP generated by system
  const [generatedOtp, setGeneratedOtp] = useState("");

  // 🔹 Controls whether OTP screen is shown
  const [showOtpScreen, setShowOtpScreen] = useState(false);

  // 🔹 Hook used to redirect to another page
  const navigate = useNavigate();

  // ✅ Function to generate 6-digit OTP
  const generateOTP = () => {
    // Generate random number between 100000–999999
    const otpValue = Math.floor(100000 + Math.random() * 900000);

    // Store OTP in state
    setGeneratedOtp(otpValue.toString());

    // Show OTP in console (for testing only)
    console.log("Generated OTP:", otpValue);
  };

  // ✅ Login function (username/password check)
  const handleLogin = () => {
    setStatus(""); // clear old messages

    // Check valid credentials
    if (
      (username === "admin" && password === "1234") ||
      (username === "user" && password === "1234")
    ) {
      // Generate OTP after login success
      generateOTP();

      // Show OTP input screen
      setShowOtpScreen(true);

      // Display success message
      setStatus("OTP sent successfully 📩");
      setError(false);

      // Store user temporarily (before OTP verification)
      localStorage.setItem("tempUser", username);

    } else {
      // Invalid login
      setStatus("Invalid Credentials ❌");
      setError(true);
    }
  };

  // ✅ OTP verification function
  const verifyOTP = () => {

    // Compare entered OTP with generated OTP
    if (otp === generatedOtp) {

      // Get user stored earlier
      const user = localStorage.getItem("tempUser");

      // Store final logged-in user
      localStorage.setItem("user", user);

      // Assign role based on username
      localStorage.setItem("role", user === "admin" ? "admin" : "user");

      // Show success message
      setStatus("OTP Verified ✅ Login Successful");
      setError(false);

      // Redirect after 1 second
      setTimeout(() => {

        // If admin → go to dashboard
        // If user → go to user page
        navigate(user === "admin" ? "/dashboard" : "/user");

      }, 1000);

    } else {
      // Wrong OTP
      setStatus("Invalid OTP ❌");
      setError(true);
    }
  };

  // ✅ Handle Enter key press
  const handleKeyPress = (e) => {

    // If Enter key is pressed
    if (e.key === "Enter") {

      // If OTP screen → verify OTP
      // Else → perform login
      showOtpScreen ? verifyOTP() : handleLogin();
    }
  };

  return (
    <div style={styles.container}>

      {/* 🔹 Header section */}
      <div style={styles.header}>
        <h2 style={{ color: "white" }}>NTPC Portal Login</h2>
      </div>

      {/* 🔹 Main login card */}
      <div style={styles.card}>

        {/* Title changes based on screen */}
        <h3 style={{ marginBottom: "20px" }}>
          {showOtpScreen ? "Enter OTP" : "Sign In"}
        </h3>

        {/* 🔹 Show Login Form OR OTP Form */}
        {!showOtpScreen ? (
          <>
            {/* Username input */}
            <input
              style={styles.input}
              placeholder="Username"
              value={username}
              onChange={(e) => setUsername(e.target.value)} // update state
              onKeyDown={handleKeyPress} // Enter key support
            />

            {/* Password input */}
            <input
              style={styles.input}
              type="password"
              placeholder="Password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              onKeyDown={handleKeyPress}
            />

            {/* Login button */}
            <button
              style={{
                ...styles.button,
                opacity: username && password ? 1 : 0.6 // disable effect
              }}
              onClick={handleLogin}
              disabled={!username || !password} // disable if empty
            >
              Login
            </button>
          </>
        ) : (
          <>
            {/* OTP input */}
            <input
              style={styles.input}
              placeholder="Enter OTP"
              value={otp}
              onChange={(e) => setOtp(e.target.value)}
              onKeyDown={handleKeyPress}
            />

            {/* Verify button */}
            <button style={styles.button} onClick={verifyOTP}>
              Verify OTP
            </button>
          </>
        )}

        {/* 🔹 Status message (error or success) */}
        {status && (
          <p style={{ color: error ? "red" : "green", marginTop: "10px" }}>
            {status}
          </p>
        )}
      </div>

      {/* 🔹 Footer */}
      <p style={styles.footer}>
        © 2026 NTPC Limited | Powering India ⚡
      </p>
    </div>
  );
}